# Generated by Django 4.0.6 on 2022-07-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('purchase_price', models.FloatField(verbose_name='Precio de Compra')),
                ('sale_price', models.FloatField(verbose_name='Precio de Venta')),
                ('measure_unit', models.CharField(choices=[('U', 'Unidad'), ('P', 'Paquete')], max_length=50, verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
