# Generated by Django 4.0.6 on 2022-08-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('purchase_price', models.FloatField(verbose_name='Precio de Compra')),
                ('sale_price', models.FloatField(verbose_name='Precio de Venta')),
                ('measure_unit', models.CharField(choices=[('U', 'Unidad'), ('P', 'Paquete')], max_length=50, verbose_name='Unidad de Medida')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
